import type { IconType } from "react-icons";
import {
	FiBook,
	FiBox,
	FiClipboard,
	FiCloud,
	FiFilePlus,
	FiHeart,
	FiInfo,
	FiLayers,
	FiSearch,
	FiShield,
	FiSliders,
	FiStar,
	FiTrendingUp,
	FiWifiOff,
	FiZap,
} from "react-icons/fi";
import {
	RiDiscordFill,
	RiFacebookFill,
	RiGithubFill,
	RiInstagramFill,
	RiLinkedinFill,
	RiTelegram2Fill,
	RiTwitterXFill,
	RiYoutubeFill,
} from "react-icons/ri";

const iconMap: Record<string, IconType> = {
	FiStar,
	FiZap,
	FiBox,
	FiBook,
	FiClipboard,
	FiHeart,
	FiFilePlus,
	FiInfo,
	FiLayers,
	FiSearch,
	FiTrendingUp,
	FiShield,
	FiCloud,
	FiSliders,
	FiWifiOff,
	RiInstagramFill,
	RiTelegram2Fill,
	RiTwitterXFill,
	RiFacebookFill,
	RiLinkedinFill,
	RiYoutubeFill,
	RiGithubFill,
	RiDiscordFill,
};

export const getIcon = (name: string): IconType | null => iconMap[name] ?? null;
